[package]
name = "websocket_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.16.0"
serde_json = "1.0.78"
url = "2.2.2"
crossterm = "0.23"
chrono = "0.4"
